### ISSUE TITLE
URL éditable pour les actualités

### ISSUE THREAD

**Issue by pboko** [vteco/vee#2]
Attention: il faut toujours rajouter dynamiquement l'id de l'actualité en fin d'URL.
Actuellement les url sont générées automatiquement: c'est un slug du titre + '__' + id de l'actu en format 5 chiffres
Ex: http://www.voseconomiesdenergie.fr/actualites/energies-renouvelables/apple-souhaite-construire-un-parc-solaire-de-530-hectares__01106

On veut pouvoir remplacer apple-souhaite-construire-un-parc-solaire-de-530-hectares  par un champ libre du backend, mais en conservant le __01106 final

**Comment by lindavte** [comment]
revision : 2674 et 2675
