### ISSUE TITLE
Récupérer le prix/mwh depuis une API de primes énergie

### ISSUE THREAD

**Issue by pboko** [vteco/vee#20]
Lors d'une demande de prime le prix est inscrit en dur dans la config du site.
Ce qui soulève plusieurs problèmes:
- l'info est doublonnée : dans vee, et dans la table partenaire de primes
- le prix sera le même pour tous les travaux

Il faut créer une API sur primes énergie, qui renvoie le prix pour un partenaire et des travaux donnés.
Ensuite, il faut que VEE consulte cette API, récupère le prix, et le passe au webservice pour faire le calcul de prime.

**Comment by lindavte** [comment]
Prime  : svn revision  : 8337
Vee : 2681 , 2682, 2683
