### ISSUE TITLE
Slug des actualités dans le backend

### ISSUE THREAD

**Issue by pboko** [vteco/vee#24]
Il est défini comme "unique" dans la base de données. Or lorsqu'on ne le précise pas, le site essaye d'enregistrer NULL en base.
Et comme NULL existe déjà en base comme slug d'actualité, cette valeur n'est plus unique, et le backend génère une erreur.

=> Il faut vérifier l'unicité du slug, uniquement si celui-ci n'est pas NULL

**Comment by lindavte** [comment]
svn 2692
