### ISSUE TITLE
Iframes: faire en sorte qu'elles puissent enregistrer les cookies

### ISSUE THREAD

**Issue by pboko** [vteco/vee#32]
Dans toutes les pages, rajouter le header HTTP P3P  (cf primesenergie)

Et rajouter les deux actions existantes sur primesénergie, qui gèrent le fichier primesenergie.fr et la redirection:
# CONFIG.yml de primes énergie

set-iframe-cookie:
  url: /setiframecookie
  param: {module: home, action: iframeCookie }

iframe-cookie-js:
  url: /iframecookie.js
  param: {module: home, action: iframeCookieJs }
  options:
    segment_separators: [.]

**Comment by lindavte** [comment]
svn : 2698, 2699, 2700, 2701, 2702
