### ISSUE TITLE
Pbm de Mapping avec QUOTATIS 

### ISSUE THREAD

**Issue by nicolasvte** [vteco/vee#33]
Devis Pompe à chaleur air air non mappé sur QUOTATIS

![fireshot screen capture 041 - - www_voseconomiesdenergie_fr_gestion_php_vendre-un-devis_1363_centrale_id 1](https://cloud.githubusercontent.com/assets/11174990/6713996/362a8bba-cd96-11e4-8ad3-642f3fb44e33.png)

**Comment by pboko** [comment]
Au vu du nom de l'erreur quotatis, c'est un lead qui avait déjà été envoyé
"Duplicate valid form"

Il faudrait vérifier en envoyant un autre lead DPE de PAC air/air à quotatis
