### ISSUE TITLE
Responsive design: le bouton principal n'est pas centré

### ISSUE THREAD

**Issue by pboko** [vteco/vee#6]
![image](https://cloud.githubusercontent.com/assets/1906061/6325390/45ebd5b0-bb47-11e4-8772-eb3c33d74671.png)

Il faut le centrer, augmenter son padding top/bottom pour qu'il soit plus haut (équivalent à l'icone du menu), et diminuer sa bordure blanche dans le cas des petits écrans.

**Comment by lindavte** [comment]
SVN Revision : 2671
