### ISSUE TITLE
Changer l'icone aide dans les résultats financement

### ISSUE THREAD

**Issue by pboko** [vteco/vee#8]
La popup d'aide s'ouvre en cliquant sur une icone de point d'interrogation.
Cette icône ne ressort pas assez aujourd'hui, on peut essayer celle-ci:
![point-dinterrogation2](https://cloud.githubusercontent.com/assets/1906061/6325746/0bf81d38-bb4b-11e4-8fc7-46a070733064.jpg)
Ou en trouver une autre, si celle-ci s'intègre mal dans l'interface.

**Comment by lindavte** [comment]
Revision : 2672
